os: osx
language: node_js
osx_image: xcode10.1
node_js: 10.15.3
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      node_js: 10.15.3
      cache:
        directories:
          - '~/.npm'
          - '.jest'
      before_script:
        - npm i -g npm@latest
      script:
        - npm ci
        - npx jest --ci
    - stage: deploy-production
      node_js: 10.15.3
      if: branch = master
      before_install:
        - openssl aes-256-cbc -K $encrypted_d778c411c1ef_key -iv $encrypted_d778c411c1ef_iv
          -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
      install:
        - bundle update
        - bundle install
      before_script: ./bin/increment_version_number
      script: ./bin/deploy_ci "production"
    - stage: deploy-beta
      node_js: 10.15.3
      if: branch = develop
      before_install:
        - openssl aes-256-cbc -K $encrypted_d778c411c1ef_key -iv $encrypted_d778c411c1ef_iv
          -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
      install:
        - bundle update
        - bundle install
      before_script: ./bin/increment_version_number
      script: ./bin/deploy_ci "staging"
